import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import SignUpForm from "./components/SignUpForm";
import { getAuth, signInWithEmailAndPassword } from "firebase/auth";
import Link from "next/link";
import firebase from "../firebase/clientApp";
import { useRouter } from "next/router";

export default function Home() {
  // console.log(clientPromise);
  const [isSignUp, setIsSignup] = useState(false);
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const router = useRouter();
  const handleClick = () => {
    setIsSignup(!isSignUp);
  };

  const handleSignIn = (e) => {
    e.preventDefault();
    if (username === "") {
      setError("Username is required");
      return;
    }
    if (password === "") {
      setError("Password is required");
      return;
    }
    setError(null);
    // login Api call
    const auth = getAuth();
    signInWithEmailAndPassword(auth, username, password)
      .then((userCredential) => {
        // Signed in
        const user = userCredential.user;
        router.push("/LoginSuccessful");

        // ...
      })
      .catch((error) => {
        const errorCode = error.code;
        const errorMessage = error.message;
        alert(errorMessage);
      });
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2 bg-gray-100">
      <Head>
        <title>Sign In and Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row items-center justify-center w-full flex-1 px-20 text-center">
        <div className="bg-white flex flex-col w-full  md:flex-row md:w-2/3 max-w-4xl shadow-2xl rounded-xl">
          <div className="p-4 md:w-3/5">
            <div className="md:text-left text-center font-bold">
              <span className="text-slate-500">Some </span>Company
            </div>
            <div className="py-10">
              <h2 className="text-3xl font-bold text-slate-500 mb-1">
                Sign in
              </h2>
              <div className="border-b-4 rounded-lg w-10 border-slate-500 inline-block"></div>
              <div className=" my-2">
                <form
                  // action="/api/login"
                  onSubmit={handleSignIn}
                  method="post"
                  className="flex flex-col gap-2 px-20 justify items-center"
                >
                  <input
                    name="email"
                    placeholder="username"
                    className="border-2 rounded-lg p-2 outline-none"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                  />
                  <input
                    name="password"
                    placeholder="password"
                    type="password"
                    className="border-2 rounded-lg p-2 outline-none"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                  />
                  <button
                    className="hover:border-2 mt-2 hover:border-slate-500 bg-slate-500 text-white rounded-xl p-2 w-2/3 inline-block font-semibold hover:bg-white hover:text-slate-500 ease-in"
                    type="submit"
                    // onClick={handleSignIn}
                  >
                    Submit
                  </button>
                  {error && <div className="text-red-500">{error}</div>}
                </form>
              </div>
            </div>
          </div>
          <div className="md:w-2/5 py-36 px-12 bg-slate-500 text-white rounded-tr-xl rounded-br-xl">
            {!isSignUp ? (
              <div>
                <h2 className="text-3xl mb-1 font-bold">New Here ?</h2>
                <div className="border-b-4 rounded-lg w-10 border-white inline-block"></div>
                <p className="mb-10">
                  Feel free to sign up with us. we are definitely not going to
                  steal your data. promise.
                </p>
                <a
                  onClick={handleClick}
                  href="#"
                  className="border-2 border-white rounded-xl px-12 py-2 inline-block font-semibold hover:bg-white hover:text-slate-500 ease-in"
                >
                  Sign Up
                </a>
              </div>
            ) : (
              <SignUpForm />
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
